//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyURLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public URL()
        {
            this.UrlStats = new HashSet<UrlStat>();
        }
    
        public int UrlId { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public int Hits { get; set; }
        public System.DateTime GeneratedDate { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<UrlStat> UrlStats { get; set; }
    }
}
