//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyURLService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlStat
    {
        public int UrlStatId { get; set; }
        public string UserAgent { get; set; }
        public string UserHostAddress { get; set; }
        public string UserLanguage { get; set; }
        public string UrlRefferer { get; set; }
        public bool IsMobile { get; set; }
        public string Browser { get; set; }
        public int MajorVersion { get; set; }
        public int UrlId { get; set; }
    
        public virtual URL URL { get; set; }
    }
}
